//
//  StyleKit.m
//  LineupBattle
//
//  Created by Anders Hansen on 08/05/15.
//  Copyright (c) 2015 Pumodo. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "StyleKit.h"


@implementation StyleKit

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawCreditWithFrame: (CGRect)frame
{
    //// Color Declarations
    UIColor* fillColor = [UIColor colorWithRed: 0.114 green: 0.584 blue: 0.169 alpha: 1];
    UIColor* fillColor2 = [UIColor colorWithRed: 0.11 green: 0.51 blue: 0.129 alpha: 1];
    UIColor* fillColor3 = [UIColor colorWithRed: 1 green: 0.875 blue: 0.294 alpha: 1];


    //// Subframes
    CGRect group = CGRectMake(CGRectGetMinX(frame), CGRectGetMinY(frame), CGRectGetWidth(frame) - 0.01, CGRectGetHeight(frame) - 0.01);


    //// Group
    {
        //// Layer_2
        {
            //// Oval Drawing
            UIBezierPath* ovalPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(CGRectGetMinX(group) + floor(CGRectGetWidth(group) * 0.00000 + 0.5), CGRectGetMinY(group) + floor(CGRectGetHeight(group) * 0.00000 + 0.5), floor(CGRectGetWidth(group) * 1.00000 - 0.49) - floor(CGRectGetWidth(group) * 0.00000 + 0.5) + 0.99, floor(CGRectGetHeight(group) * 1.00000 - 0.49) - floor(CGRectGetHeight(group) * 0.00000 + 0.5) + 0.99)];
            [fillColor setFill];
            [ovalPath fill];
        }


        //// Layer_3
        {
            //// Oval 2 Drawing
            UIBezierPath* oval2Path = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(CGRectGetMinX(group) + floor(CGRectGetWidth(group) * 0.09207 - 0.17) + 0.67, CGRectGetMinY(group) + floor(CGRectGetHeight(group) * 0.09207 - 0.49) + 0.99, floor(CGRectGetWidth(group) * 0.90488 - 0.5) - floor(CGRectGetWidth(group) * 0.09207 - 0.17) + 0.33, floor(CGRectGetHeight(group) * 0.90488 + 0.18) - floor(CGRectGetHeight(group) * 0.09207 - 0.49) - 0.67)];
            [fillColor2 setFill];
            [oval2Path fill];
        }


        //// Layer_4
        {
            //// Oval 3 Drawing
            UIBezierPath* oval3Path = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(CGRectGetMinX(group) + floor(CGRectGetWidth(group) * 0.11841 + 0.07) + 0.43, CGRectGetMinY(group) + floor(CGRectGetHeight(group) * 0.11841 + 0.07) + 0.43, floor(CGRectGetWidth(group) * 0.88159 - 0.06) - floor(CGRectGetWidth(group) * 0.11841 + 0.07) + 0.12, floor(CGRectGetHeight(group) * 0.88159 - 0.06) - floor(CGRectGetHeight(group) * 0.11841 + 0.07) + 0.12)];
            [fillColor3 setFill];
            [oval3Path fill];
        }


        //// Layer_5
        {
            //// Group 5
            {
                //// Bezier Drawing
                UIBezierPath* bezierPath = UIBezierPath.bezierPath;
                [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(group) + 0.50453 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.39770 * CGRectGetHeight(group))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.46897 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.40737 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.49038 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.39770 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.47853 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.40093 * CGRectGetHeight(group))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.44558 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.43232 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.45940 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.41383 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.45159 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.42214 * CGRectGetHeight(group))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.43278 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.46601 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.43953 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.44252 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.43528 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.45376 * CGRectGetHeight(group))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.42904 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.50251 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.43029 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.47829 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.42904 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.49046 * CGRectGetHeight(group))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.43278 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.53807 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.42904 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.51416 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.43029 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.52601 * CGRectGetHeight(group))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.44495 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.57083 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.43528 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.55014 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.43933 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.56106 * CGRectGetHeight(group))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.46772 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.59484 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.45056 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.58060 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.45816 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.58861 * CGRectGetHeight(group))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.50266 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.60419 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.47728 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.60108 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.48893 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.60419 * CGRectGetHeight(group))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.55164 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.58641 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.52387 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.60419 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.54020 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.59827 * CGRectGetHeight(group))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.57317 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.53868 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.56307 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.57455 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.57025 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.55865 * CGRectGetHeight(group))];
                [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.65864 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.53868 * CGRectGetHeight(group))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.60873 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.63664 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.65282 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.58153 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.63619 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.61418 * CGRectGetHeight(group))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.50331 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.67033 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.58129 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.65910 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.54613 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.67033 * CGRectGetHeight(group))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.43685 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.65816 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.47918 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.67033 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.45702 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.66627 * CGRectGetHeight(group))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.38538 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.62416 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.41667 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.65005 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.39951 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.63872 * CGRectGetHeight(group))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.35231 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.57207 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.37124 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.60961 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.36021 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.59224 * CGRectGetHeight(group))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.34046 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.50562 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.34441 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.55189 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.34046 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.52975 * CGRectGetHeight(group))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.35138 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.43606 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.34046 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.48066 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.34409 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.45748 * CGRectGetHeight(group))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.38352 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.38053 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.35866 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.41464 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.36936 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.39613 * CGRectGetHeight(group))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.43530 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.34403 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.39763 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.36492 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.41492 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.35276 * CGRectGetHeight(group))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.50517 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.33093 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.45567 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.33529 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.47898 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.33093 * CGRectGetHeight(group))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.56039 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.33842 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.52430 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.33093 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.54271 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.33343 * CGRectGetHeight(group))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.60781 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.36119 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.57807 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.34341 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.59388 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.35100 * CGRectGetHeight(group))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.64182 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.39925 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.62175 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.37139 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.63307 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.38407 * CGRectGetHeight(group))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.65679 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.45322 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.65054 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.41445 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.65554 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.43243 * CGRectGetHeight(group))];
                [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.57007 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.45322 * CGRectGetHeight(group))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.50453 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.39770 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.56421 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.41621 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.54237 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.39770 * CGRectGetHeight(group))];
                [bezierPath closePath];
                bezierPath.miterLimit = 4;

                [fillColor setFill];
                [bezierPath fill];
            }
        }
    }
}

+ (void)drawPersonWithFrame: (CGRect)frame
{
    //// Color Declarations
    UIColor* fillColor4 = [UIColor colorWithRed: 0.114 green: 0.527 blue: 0.128 alpha: 1];


    //// Subframes
    CGRect obj = CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.00252 + 0.21) + 0.29, CGRectGetMinY(frame) + floor(CGRectGetHeight(frame) * 0.00000 + 0.5), floor(CGRectGetWidth(frame) * 1.00395 + 0.04) - floor(CGRectGetWidth(frame) * 0.00252 + 0.21) + 0.17, floor(CGRectGetHeight(frame) * 1.00000 + 0.5) - floor(CGRectGetHeight(frame) * 0.00000 + 0.5));


    //// obj
    {
        //// Bezier Drawing
        UIBezierPath* bezierPath = UIBezierPath.bezierPath;
        [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(obj) + 0.50000 * CGRectGetWidth(obj), CGRectGetMinY(obj) + 0.51126 * CGRectGetHeight(obj))];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(obj) + -0.00000 * CGRectGetWidth(obj), CGRectGetMinY(obj) + 0.87501 * CGRectGetHeight(obj)) controlPoint1: CGPointMake(CGRectGetMinX(obj) + 0.22385 * CGRectGetWidth(obj), CGRectGetMinY(obj) + 0.51126 * CGRectGetHeight(obj)) controlPoint2: CGPointMake(CGRectGetMinX(obj) + -0.00000 * CGRectGetWidth(obj), CGRectGetMinY(obj) + 0.67412 * CGRectGetHeight(obj))];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(obj) + 0.03030 * CGRectGetWidth(obj), CGRectGetMinY(obj) + 1.00000 * CGRectGetHeight(obj)) controlPoint1: CGPointMake(CGRectGetMinX(obj) + -0.00000 * CGRectGetWidth(obj), CGRectGetMinY(obj) + 0.91892 * CGRectGetHeight(obj)) controlPoint2: CGPointMake(CGRectGetMinX(obj) + 0.01070 * CGRectGetWidth(obj), CGRectGetMinY(obj) + 0.95946 * CGRectGetHeight(obj))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(obj) + 0.96970 * CGRectGetWidth(obj), CGRectGetMinY(obj) + 1.00000 * CGRectGetHeight(obj))];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(obj) + 1.00000 * CGRectGetWidth(obj), CGRectGetMinY(obj) + 0.87501 * CGRectGetHeight(obj)) controlPoint1: CGPointMake(CGRectGetMinX(obj) + 0.98930 * CGRectGetWidth(obj), CGRectGetMinY(obj) + 0.95946 * CGRectGetHeight(obj)) controlPoint2: CGPointMake(CGRectGetMinX(obj) + 1.00000 * CGRectGetWidth(obj), CGRectGetMinY(obj) + 0.91892 * CGRectGetHeight(obj))];
        [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(obj) + 0.50000 * CGRectGetWidth(obj), CGRectGetMinY(obj) + 0.51126 * CGRectGetHeight(obj)) controlPoint1: CGPointMake(CGRectGetMinX(obj) + 1.00000 * CGRectGetWidth(obj), CGRectGetMinY(obj) + 0.67412 * CGRectGetHeight(obj)) controlPoint2: CGPointMake(CGRectGetMinX(obj) + 0.77615 * CGRectGetWidth(obj), CGRectGetMinY(obj) + 0.51126 * CGRectGetHeight(obj))];
        [bezierPath closePath];
        [fillColor4 setFill];
        [bezierPath fill];


        //// Oval Drawing
        UIBezierPath* ovalPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(CGRectGetMinX(obj) + floor(CGRectGetWidth(obj) * 0.14727 + 0.39) + 0.11, CGRectGetMinY(obj) + floor(CGRectGetHeight(obj) * 0.00000 + 0.5), floor(CGRectGetWidth(obj) * 0.85316 + 0.39) - floor(CGRectGetWidth(obj) * 0.14727 + 0.39), floor(CGRectGetHeight(obj) * 0.55405 + 0.5) - floor(CGRectGetHeight(obj) * 0.00000 + 0.5))];
        [fillColor4 setFill];
        [ovalPath fill];
    }
}

@end
