//
//  StyleKit.h
//  LineupBattle
//
//  Created by Anders Hansen on 08/05/15.
//  Copyright (c) 2015 Pumodo. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKit : NSObject

// Drawing Methods
+ (void)drawCreditWithFrame: (CGRect)frame;
+ (void)drawPersonWithFrame: (CGRect)frame;

@end
